name: learn-github-actions

on:
  push:
    branches: ['master', 'release', 'development']

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:

      # init
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install

      # extract branch name
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5


      - run: echo ${{ steps.branch-name.outputs.current_branch }}

      # set tagname
      - run: echo ${{ env.TAG_NAME }}
        env:
          TAG_NAME: "${{ ( steps.branch-name.outputs.current_branch == 'development' && 'alpha' ) || ( steps.branch-name.outputs.current_branch == 'release' && 'beta' ) || 'latest' }}"
          
      # set version number
      - run: npm run set-publish-version

      # npm publish
#      - run: npm publish --tag ${ env.TAG_NAME }
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
