name: learn-github-actions
on:
  push
    branches: [ 'master', 'release', 'development' ]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # init
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      # extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run cehco ${ BRANCH_NAME }
      # npm publish
      - run: npm publish --tag ${ BRANCH_NAME }
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
